ci:
  autoupdate_commit_msg: "chore: Update pre-commit hooks"
exclude: ^dist/
repos:
  - repo: local
    hooks:
      - id: build
        name: build
        entry: pnpm build
        language: system
        files: ^$
        always_run: true
      - id: lint
        name: lint
        entry: pnpm lint:fix
        language: system
        types: [file, ts]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 3.0.3
    hooks:
      - id: prettier-conda
        files: "\\.(json|md|yml|yaml)$"
  - repo: https://github.com/crate-ci/typos
    rev: 1.16.17
    hooks:
      - id: typos
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 4.4.0
    hooks:
      - id: trailing-whitespace-conda
      - id: end-of-file-fixer-conda
